# Generated by Django 4.1.5 on 2023-01-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('game', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Participant', max_length=255)),
                ('roll', models.CharField(max_length=255, unique=True)),
                ('branch', models.CharField(default=' ', max_length=100)),
                ('year', models.CharField(default=' 1st Year', max_length=50)),
                ('game_id', models.CharField(default=' ', max_length=255)),
                ('VALO', models.BooleanField(default=False)),
                ('CODM', models.BooleanField(default=False)),
                ('FIFA', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.team')),
            ],
        ),
    ]
